### ISSUE TITLE
Vesta and Ceres normal map issues

### ISSUE THREAD

**Issue by raidernick** [KSP-RO/RSS-Textures#17]
I am making this as an issue that was reported on the forum. Apparently the normal maps for Vesta and Ceres are bad in the merge from @pap1723 and need to be fixed. I can confirm that there is _something_ wrong with the lighting but I can't tell if it's really the normal map. Apparently the guy who asked this asked Thomas about it in regards to kopernicus and he said that was the issue.

@PhineasFreak 
@pap1723 

Please check this if you can.

**Comment by PhineasFreak** [comment]
I reported it before releasing the 1.3.1 version of RSS but i never got a response/confirmation: https://github.com/KSP-RO/RealSolarSystem/issues/127. This does not only affect Ceres and Vesta but all bodies inherited by RSS Planets & Moons Expanded (moons of Uranus).

I re-exported the normal maps locally but either this is not the problem or, most probably, i failed to do so correctly. But i can 100% confirm that something in these bodies (configs or textures) is broken.

Surpisingly, the rest of the RSS Planets & Moons Expanded works perfectly under the same Kopernicus versions with minor/no changes.

**Comment by raidernick** [comment]
@PhineasFreak seeing as how this adds useful bodies and appears to be abandoned, is this a mod we'd want to pick up as part of rss or something?

**Comment by PhineasFreak** [comment]
I have already adopted and updated it for the newer KSP versions (also fixed the incorrect inclinations from the last iteration and the SOIs being under the surface for many of the moonlets): https://github.com/PhineasFreak/RSSExpansion

It is still a bit of WIP regarding Principia support though. Some orbital data for satellite bodies (Ida I Dactyl and Orcus I Vanth) cannot be provided by the JPL HORIZONS interface.

**Comment by raidernick** [comment]
@PhineasFreak @pap1723 so is there no way to fix this? At the very least RSS bodies HAVE to be fixed and a new version of RSS or textures released. I wasn't aware that RSS/textures had these issues when I pushed to have it released to get RO done as I have never visited these bodies before and I don't use any expanded mods.

**Comment by PhineasFreak** [comment]
~~Are we sure that the textures are to blame? Because i remember using the Scaled Textures pack with the pre-"breaking ocean" Kopernicus releases (for KSP 1.3.1) and it did not happen.~~

**Edit 1:** so, it is definitely caused by the normal maps. Uncommenting the normal map texture definitions in the Kopernicus body config results to bodies being lit correctly. ~~Next step is to try and convert them into .dds, as i did with the rest of the RSSExpanded normal maps.~~

**Edit 2:** ~~these normal map textures are saved using the L8 format instead of RGBA. Unity probably doesn't like this format (and that's why RSSExpanded did not have the same problem - all normal maps use the DXT5nm format).~~

**Edit 3:** ~~just opening the .png files and re-saving them (L8 --> RGBA conversion) fixes everything. I will go ahead though and:~~

* ~~convert the into DXT5nm~~
* ~~rename them to follow the rest of the RSS textures conventions (and update the RSS Kopernicus configs as required)~~

**Edit 4:** nope...i was wrong. I though that the above fixed the problems but then i noticed that Kopernicus did not load the texture at all. It turns out that i forgot to change the extension back to .png (from .dds - while testing) and when i did so the normals were broken again...

**Edit 5:** seems that the only way to fix this is to recreate the normal maps from scratch. On another note, if a closer look at the surface of the bodies is taken, you can see the Eeloo normal map placed on top of every other texture. Maybe that has also something to do with the broken normal maps? Every single one of these bodies use Eeloo as a template.

**Edit 6:** OK, i re-exported the normal maps via gimp + the included height maps. Bodies work but i still want to check the Eeloo normal map also appearing.

**Comment by raidernick** [comment]
@PhineasFreak I'm not exactly sure what you mean by the normal maps are based off of eeloo. Are they modified eeloo normals or do they call the eeloo normal as a dependency? If they are modified how can the original normal still exist inside the same image? If not, what config is calling the eeloo normal to be placed on top of everything and why would it do that.

**Comment by PhineasFreak** [comment]
It is a bit complicated and i am not sure if i can give a good enough explanation: Custom Kopernicus configs have to be derived from known celestial bodies templates. These are the stock bodies and the templates carry every information on how a celestial body is structured.

In our case, all these bodies use the stock Eeloo body template, possibly because it is an icy world and easy to modify (it's just a rock). But, for some reason, our Kopernicus configs use both the custom textures (color & normal) that we supply **and** the stock Eeloo normal texture. It does not override the stock normal map but it adds to it.

It is relatively easy to see that: go to the tracking station and focus on a random Uranus moon. Notice that there are lines on the body surface that cannot be explained by the body structure. You can switch between the moons and see that, even if they have different surfaces, these lines are always there.

**Comment by raidernick** [comment]
Ok, that makes sense. I should be asking then WHY our configs are using both normal maps then instead of just the new normal map. I don't see any of the other bodies doing that.

**Comment by PhineasFreak** [comment]
We had the same problems with Earth: the internal structure of Kopernicus changed and required from us to add custom Ocean nodes in order to get the oceans back. For KSP 1.4, @KerbasAdAstra had to change the Earth config again in order to make RSS compatible the newer Kopernicus changes.

I guess that one of these Kopernicus updates "broke" something with these configs. Do note that these bodies have not actually been updated for a long time (KSP 1.0.5 was the last compatible version). They might even need a total rework.

Similarly, i found out that the RSSExpansion pack **will** definitely require a rework, at least to re-export all normal maps: textures had been converted into .dds format but the Kopernicus configs were searching for .png files. The result was that no normal maps appeared in-game, making me assume that they worked perfectly. Stupid me...

**Comment by Kerbas-ad-astra** [comment]
I'm not sure I see the Eeloo connection...it seems to me that there's a texture getting rotated or flipped or squashed.  Changing those planets to use different bodies as templates still produces the ~90-degree lighting offset and (for the Uranian moons but not Ceres or Vesta) weird polar striations.  However, when I switch the ScaledVersion texture references to e.g. the Moon's textures, they light up correctly.

The change that I was dealing with was that Kopernicus (or possibly the game itself) used to merge Earth's PQSMods into their counterparts from the Kerbin template, but now (in 1.4) it adds them to the planet.  I dealt with that by telling Kopernicus to remove Kerbin's PQSMods.  Several other worlds use template bodies without removing all (or even any) of their PQSMods, but as you can see in [this commit](https://github.com/Kerbas-ad-astra/kittopia-dumps/commit/19188c7a31f20e3665b7a69bea6e778c2e96ecce) (comparing Kittopia's dumps of the RSS planets from KSP 1.3.1 to 1.4.2) only Earth's (Kerbin's) PQSMods changed to an appreciable extent between versions.  It may be the case that something changed in Kerbin's loading to accommodate changes like the new launch pad system.  Even if this were an issue for the new bodies, it wouldn't affect the appearance of the planet in scaled space.

**Comment by PhineasFreak** [comment]
Let me do a demonstration on the whole Eeloo thing:

* **Ceres**
* **Vesta**
* **Miranda**
* **Ariel**
* **Umbriel**
* **Titania**
* **Oberon**

Now, compare them to **[Eeloo](https://i.ytimg.com/vi/29MWXelqyyg/maxresdefault.jpg)**. Note how they (re)use the Eeloo normal map, even after fixing/updating the normal maps (with Umbriel being the most obvious - it appears almost as an Eeloo clone). Only Ceres seems to work as expected.

The Earth KSP 1.4 compatibility PR was just an example on how older and working Kopernicus configs can fail to work on newer Kopernicus releases. As i mentioned earlier, the configs for these bodies have not really been updates since KSP 1.0.5, so they could have all kinds of issues.

In any case, i re-exported the normal maps via the height maps (although they might not be as perfect as they were before) and, as you see from the screenshots, everything works OK. I will do a double PR on both the RealSolarSystem and the RSS-Textures repositories to include these on the main branch.

**Edit:** removed sample images.

**Comment by raidernick** [comment]
@PhineasFreak thank you for fixing this. Once you make those prs i'll give them a test and if good push out the new releases.

**Comment by PhineasFreak** [comment]
So, consider me a moron and ignore **EVERYTHING** that i said about the whole "Eeloo" thingy. Once again i forgot that Kopernicus requires not only the correct texture name but also the correct texture extension. I left the **.png** extensions for the normal maps while i was testing with the **.dds** ones...

After i corrected those...tada! No more Eeloo normal maps!

PRs for testing are up:

* RSS configs: https://github.com/KSP-RO/RealSolarSystem/pull/140
* RSS textures: https://github.com/KSP-RO/RSS-Textures/pull/19

**Comment by raidernick** [comment]
prs were merged and this issue is fixed, awaiting release
